services:
    AppBundle\Event\Subscriber\BuildDemoSchemaSubscriber:
        autoconfigure: true
        arguments:
            - '@=service("kernel").locateResource("@AppBundle/Resources/schema/demo.yaml")'

    app.installer.demo_installer:
        autowire: true
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\PlatformDemoInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
        tags:
            - { name: ezplatform.installer, type: ezplatform-demo }
